name: CI pipeline for pasteLite

on: 
  push:
    branches: 
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build and Test pastelite app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v3
        with: 
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-{{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run app with Docker Compose
        run: |
          docker compose up --build -d
          sleep 10
          docker ps
      
      - name: clean up 
        run: docker compose dowm

